### ISSUE TITLE
Compile errors in RVOpenGLView

### ISSUE THREAD

**Issue by daviddelmonte** [Ciechan/Revolved#2]
Perhaps a file missing?

RVOpenGLView.m:115:5: Implicit declaration of function 'glRenderbufferStorageMultisampleAPPLE' is invalid in C99

RVOpenGLView.m:115:63: Use of undeclared identifier 'GL_RGBA8_OES'

RVOpenGLView.m:120:63: Use of undeclared identifier 'GL_DEPTH_COMPONENT24_OES'

RVOpenGLView.m:131:5: Implicit declaration of function 'glDiscardFramebufferEXT' is invalid in C99

Revolved/RVOpenGLView.m:133:23: Use of undeclared identifier 'GL_READ_FRAMEBUFFER_APPLE'

Use of undeclared identifier 'GL_DRAW_FRAMEBUFFER_APPLE'

Implicit declaration of function 'glResolveMultisampleFramebufferAPPLE' is invalid in C99

RVOpenGLView.m:139:29: Use of undeclared identifier 'GL_READ_FRAMEBUFFER_APPLE'

RVOpenGLView.m:209:51: Use of undeclared identifier 'GL_BGRA'

RVOpenGLView.m:224:23: Use of undeclared identifier 'GL_DRAW_FRAMEBUFFER_APPLE'

RVOpenGLView.m:225:23: Use of undeclared identifier 'GL_READ_FRAMEBUFFER_APPLE'

**Comment by Ciechan** [comment]
Xcode6 no longer implicitly imports OpenGL headers, I've just pushed the fix!

**Comment by daviddelmonte** [comment]
Thanks!!!
